### ISSUE TITLE
Scenes exposed as switches keep 'on' state after triggering

### ISSUE THREAD

**Issue by technicalpickles** [home-assistant/homebridge-homeassistant#42] opened 2016-09-21 21:54 UTC
Consider something like this:
- a scene in HA named Good Night
- homebridge-homeassistant exposes this as a switch
- in the Home iOS app, create a Good Night scene to switch Good Night on
- tell siri "Good Night"

After telling Siri Good Night, that turns on the Good Night switch, which tells Home Assistant to activate the scene. That is all good. However, the next day you check Home, and it shows the Good Night switch as still on. I haven't confirmed this, but I think this will prevent using Good Night a second time.

**Comment by rafaelmagu** [comment] 2016-09-21 22:10
It doesn't prevent it, but it does mean you have to tell Siri "Good Night" twice, from experience.

**Comment by maddox** [comment] 2016-09-21 23:50
We could always immediately toggle it back to off in the accessory if its ha source is a switch. 

But this is just hax on hax tbh.

**Comment by jfautley** [comment] 2016-09-30 22:32
Was there a reason that HomeKit's 'StatelessProgrammableSwitch' couldn't be used to drive scenes?

Looks like @maddox already had that particular thought [here](https://github.com/KhaosT/HAP-NodeJS/issues/134#issuecomment-141207344).

If not, I think having the scene switch 'reset' after a period of time would be useful as the HomeKit app cheerily tells me that a switch is left on when I've triggered a scene. The argument of it being hax on hax is ultimately valid, but surely the whole notion of an unofficial HomeKit interface is a hack, right? :)

**Comment by maddox** [comment] 2016-09-30 23:06
I can't remember if that idea fell flat, or I couldn't find that thread again to figure out how to do it. Lol.

**Comment by maddox** [comment] 2016-09-30 23:07
One other thing that's super lame is that HomeKit scenes DO have on/off state. :/

But they seem to get resolved based on overall state of accessories.

**Comment by MaKin211** [comment] 2016-10-24 04:36
I also faced that 'problem' yesterday. In order to enable the scene a second time, you first have to disable it which takes a few seconds and then can re-enable it. This is really unnecessary.

I set up boolean_inputs in HA for my scenes (on: enable scene / off: turn off lights) but it somehow messes up the colors...

**Comment by kolossboss** [comment] 2016-11-15 21:10
Same problem here. 
On iOS9 this works without any problems. On iOS 9 you could "turn on" a switch or scene even the status was already "on". But I dont know if its a general iOS 10 issue. With Hesperus.app (great homekit app) you still  can do this on iOS10. 
I have this problem with blinds (cant stop them anymore) and dimmers (wrong state because of wallswitch), too. 
Very annoying. I hope you gus can fix the apple shit.:-)

**Comment by robbiet480** [comment] 2017-01-13 20:58
Closed via #88.

**Comment by heathpitts** [comment] 2017-02-04 14:05
Did this issue ever get resolved?

**Comment by heathpitts** [comment] 2017-02-28 20:43
@robbiet480 can this issue be reopened? I still have to go in and turn the scene off in the Home app even with the latest code

**Comment by tobre6** [comment] 2017-02-28 20:47
I reopened as this issue persists.

**Comment by andyrooo82** [comment] 2017-03-15 14:12
I installed this plugin yesterday - absolutley awesome btw!
I can confirm this bug is still apparent. The switch stays on after the scene is started. Bulbs seem to be fine though.

**Closed** 2017-05-05 20:31 UTC
Labels: bug
