### ISSUE TITLE
RGB support

### ISSUE THREAD

**Issue by bhaap** [home-assistant/homebridge-homeassistant#84] opened 2016-12-29 16:44 UTC
RGB and RGBW support is needed. Somthing like this may help?

There seem to bee alot of HSB(HSV) to RGB converters out there. Maby this can help:
https://gist.github.com/eyecatchup/9536706

**Comment by tobre6** [comment] 2016-12-30 21:29
I have been playing round with this issue a couple of days now. I got this working with good results. Please see PR https://github.com/home-assistant/homebridge-homeassistant/pull/85

**Comment by bhaap** [comment] 2016-12-30 21:43
Oh nice.. tried to install yours the crude way of just copy pasting your git onto my computer but im getting this error when trying to start my homebridge now

Error: Cannot find module 'request'

How would one go about installing your modified homebridge-homeassistant? :D
Or should i just wait for the PR to be commited :D

**Comment by tobre6** [comment] 2016-12-30 21:48
I'm sure there is something else wrong, because I changed basically only light.js accessory file. Try to replace that.

**Comment by bhaap** [comment] 2016-12-30 21:49
Ok will try

**Comment by bhaap** [comment] 2016-12-30 22:12
Hmm well it seems it has issues with siri. When changing color manually it only sets them to a maximum of 255. But after issuing a change color command with siri it tries to change color beyond that spectrum resulting in nothing.

Log:
Pre chatting to siri:
[2016-12-30 23:06:07] [HomeAssistant] Successfully set power state on the 'Vardagsrumsbordlamp-RGB' to on
[2016-12-30 23:06:07] [HomeAssistant] Successfully set brightness on the 'Vardagsrumsbordlamp-RGB' to 100
[2016-12-30 23:06:13] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:14] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 255,251,5
[2016-12-30 23:06:27] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:27] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 255,0,60
[2016-12-30 23:06:29] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:29] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 255,0,208
[2016-12-30 23:06:39] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:39] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 255,34,0
[2016-12-30 23:06:40] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:40] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 0,0,255
[2016-12-30 23:06:41] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:06:41] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 0,255,42

After chatting to siri and asking her to change to color to red (nothing happend and after that i cannot change color of the lamp:

[2016-12-30 23:08:35] [HomeAssistant] Setting power state on the 'Vardagsrumsbordlamp-RGB' to on
[2016-12-30 23:08:35] [HomeAssistant] Setting brightness on the 'Vardagsrumsbordlamp-RGB' to 100
[2016-12-30 23:08:35] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 650,0,0
[2016-12-30 23:08:35] [HomeAssistant] Successfully set power state on the 'Vardagsrumsbordlamp-RGB' to on
[2016-12-30 23:08:35] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:08:35] [HomeAssistant] Successfully set brightness on the 'Vardagsrumsbordlamp-RGB' to 100
[2016-12-30 23:08:56] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 509,650,0
[2016-12-30 23:08:56] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:10:50] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 650,314,0
[2016-12-30 23:10:50] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:10:51] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 650,0,22
[2016-12-30 23:10:51] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:10:51] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 641,104,650
[2016-12-30 23:10:51] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
[2016-12-30 23:10:53] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 520,650,0
[2016-12-30 23:10:53] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined

To get it working again i need to power cycle the lamp in home.

**Comment by bhaap** [comment] 2016-12-30 22:14
Also the corresponding colors to the hue with some saturation is well not accurate :P

**Comment by tobre6** [comment] 2016-12-30 22:27
I confirmed siri issue. I will look into this.
But colors corresponding to real life is tricky. It depends on the leds and hardware. :)

**Comment by bhaap** [comment] 2016-12-30 22:46
Another way of doing this would be to have a mqtt scetch that reports both RGB and HSV values of the lamp and using the HSV values here on the homebrige plugin and the rgb ones on HASS. 

This scetch has all that but i am unable to compile it due to some iram issues.

https://github.com/ge0rg/WiFI-RGBWW-module

**Comment by bhaap** [comment] 2016-12-30 23:06
But that would be only for mqtt and not for all RGB/RGBW/RGBWW lamps :D

**Comment by bhaap** [comment] 2016-12-30 23:14
here is the debug:

`  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":32,"iid":8,"value":true},{"aid":32,"iid":9,"value":100},{"aid":32,"iid":15,"value":350},{"aid":32,"iid":16,"value":25}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value true +0ms
[2016-12-31 00:13:29] [HomeAssistant] Setting power state on the 'Vardagsrumsbordlamp-RGB' to on
  Accessory [Homebridge] Setting Characteristic "Brightness" to value 100 +2ms
[2016-12-31 00:13:29] [HomeAssistant] Setting brightness on the 'Vardagsrumsbordlamp-RGB' to 100
  Accessory [Homebridge] Setting Characteristic "Hue" to value 350 +2ms
  Accessory [Homebridge] Setting Characteristic "Saturation" to value 25 +1ms
[2016-12-31 00:13:29] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to 650,488,515
  EventedHTTPServer [::ffff:192.168.1.174] Muting event '32.16' notification for this connection since it originated here. +61ms
[2016-12-31 00:13:29] [HomeAssistant] Successfully set power state on the 'Vardagsrumsbordlamp-RGB' to on
[2016-12-31 00:13:29] [HomeAssistant] Successfully set rgb on the 'Vardagsrumsbordlamp-RGB' to undefined
  EventedHTTPServer [::ffff:192.168.1.174] Muting event '32.15' notification for this connection since it originated here. +20ms
[2016-12-31 00:13:29] [HomeAssistant] Successfully set brightness on the 'Vardagsrumsbordlamp-RGB' to 100
  EventedHTTPServer [::ffff:192.168.1.174] HTTP Response is finished +4ms

`

**Comment by bhaap** [comment] 2016-12-30 23:21
The difference in chaning color manually and asking siri to do so is that siri sends 4 commands (on, brightness, hue and saturation) and when only changing colors only hue and saturation is sent.

**Comment by tobre6** [comment] 2016-12-31 09:22
I'm using this sketch on my hardware:
https://github.com/tobre6/mqtt-h801

I will investigate siri issue.

**Comment by tobre6** [comment] 2016-12-31 11:42
I fixed siri issue.

**Comment by tobre6** [comment] 2016-12-31 15:38
#85

**Comment by cmsimike** [comment] 2017-02-15 20:58
Is closed by today's merging of !85?

**Closed** 2017-02-15 21:59 UTC
Labels: feature-request
