### ISSUE TITLE
Error in light.js stopping Homebridge

### ISSUE THREAD

**Issue by jsg4** [home-assistant/homebridge-homeassistant#32] opened 2016-08-29 12:56 UTC
Running HomeAssistant 0.27 and just updated to latest Homebridge and Homebridge-homeassistant. Seeing this error which stops Homebridge. Also I am not seeing rollershutters or door locks either, I added rollershutters to the config.json.

http://pastebin.com/gPTAtWZ1

**Comment by shmuelzon** [comment] 2016-09-11 06:54
Is this something you can easily reproduce?
Can you please add the below modification on your setup so I can see what kind of event you're receiving right before the exception? Until now, I haven't seen and event that didn't include and `old_state`.
 
```patch
diff --git a/index.js b/index.js
index 954441a..326d5f7 100644
--- a/index.js
+++ b/index.js
@@ -61,6 +61,8 @@ function HomeAssistantPlatform(log, config, api){
     if (data.event_type != 'state_changed')
       return;
 
+    console.log('Got event:', data);
+
     var numAccessories = this.foundAccessories.length;
     for (var i = 0; i < numAccessories; i++) {
       var accessory = this.foundAccessories[i];
```

**Comment by jsg4** [comment] 2016-09-12 12:45
I'm sorry but do not know how to do that in order to see better logging? Also just saw this error now too.

http://pastebin.com/kuvQdSAD

**Comment by shmuelzon** [comment] 2016-09-13 07:02
The new error messages don't have anything to do with Home Assistant, so I can't help there. As for the error in the first post, I'll do what I can.
To make the modification I requested, it depends on where you installed homebridge-homeassistant. If you installed it globally (used `npm install -g`) then you can find where it's located by running `npm root -g`.
In the location it will print out, you will find the `homebridge-homeassistant` directory. Edit the `index.js` file in that directory. You will need to add the line I suggested
```js
console.log('Got event:', data);
```
at around line 63. Save the file an restart homebridge. Next time you will see that error again, please post the logs and I hope we can find a solution.

Thanks!

**Comment by jsg4** [comment] 2016-09-13 17:29
Thanks so much, put that in and update this if and when there's an error.

**Comment by jsg4** [comment] 2016-09-13 21:27
@shmuelzon looks like group.shades is throwing it? What's weird is that rollershutters do not come through as a device in homebridge from homeassistant.

`Got event: { event_type: 'state_changed',
  origin: 'LOCAL',
  data: 
   { entity_id: 'group.shades',
     old_state: 
      { last_changed: '2016-09-13T21:15:28.758144+00:00',
        entity_id: 'group.shades',
        state: 'unknown',
        attributes: [Object],
        last_updated: '2016-09-13T21:15:28.758144+00:00' },
     new_state: 
      { last_changed: '2016-09-13T21:15:33.890489+00:00',
        entity_id: 'group.shades',
        state: 'closed',
        attributes: [Object],
        last_updated: '2016-09-13T21:15:33.890489+00:00' } },
  time_fired: '2016-09-13T21:15:33.979403+00:00' }
Got event: { event_type: 'state_changed',
  origin: 'LOCAL',
  data: 
   { entity_id: 'group.shades',
     old_state: 
      { last_changed: '2016-09-13T21:15:28.758144+00:00',
        entity_id: 'group.shades',
        state: 'unknown',
        attributes: [Object],
        last_updated: '2016-09-13T21:15:28.758144+00:00' },
     new_state: 
      { last_changed: '2016-09-13T21:15:33.890489+00:00',
        entity_id: 'group.shades',
        state: 'closed',
        attributes: [Object],
        last_updated: '2016-09-13T21:15:33.890489+00:00' } },
  time_fired: '2016-09-13T21:15:33.979403+00:00' }
Got event: { event_type: 'state_changed',
  origin: 'LOCAL',
  data: 
   { entity_id: 'switch.window_4_switch_15',
     old_state: null,
     new_state: 
      { last_changed: '2016-09-13T21:15:34.033323+00:00',
        entity_id: 'switch.window_4_switch_15',
        state: 'off',
        attributes: [Object],
        last_updated: '2016-09-13T21:15:34.033323+00:00' } },
  time_fired: '2016-09-13T21:15:34.060759+00:00' }
/usr/local/lib/node_modules/homebridge-homeassistant/accessories/switch.js:29
    if (old_state.state == new_state.state)
                 ^

TypeError: Cannot read property 'state' of null
    at Object.HomeAssistantSwitch.onEvent (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/switch.js:29:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:71:19)
    at emitOne (events.js:77:13)
    at EventSource.emit (events.js:169:7)
    at _emit (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:181:17)
    at parseEventStreamLine (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:196:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:159:11)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
pi@raspberrypi:~ $ `

**Comment by robbiet480** [comment] 2016-09-13 21:35
@jsg4 Looks like this will be an easy fix. Did you get this error shortly after restarting Home Assistant or something? Trying to figure out why your `old_state` is missing.

**Comment by jsg4** [comment] 2016-09-13 21:43
Actually seeing this more with other things too.

Got event: { time_fired: '2016-09-13T21:35:28.672353+00:00',
  event_type: 'state_changed',
  origin: 'LOCAL',
  data: 
   { old_state: null,
     new_state: 
      { last_changed: '2016-09-13T21:35:28.672264+00:00',
        last_updated: '2016-09-13T21:35:28.672264+00:00',
        entity_id: 'light.front_door_light_level_21',
        state: 'off',
        attributes: [Object] },
     entity_id: 'light.front_door_light_level_21' } }
/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:43
    if (old_state.state != new_state.state) {
                 ^

TypeError: Cannot read property 'state' of null
    at Object.HomeAssistantLight.onEvent (/usr/local/lib/node_modules/homebridge-homeassistant/accessories/light.js:43:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/index.js:71:19)
    at emitOne (events.js:77:13)
    at EventSource.emit (events.js:169:7)
    at _emit (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:181:17)
    at parseEventStreamLine (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:196:9)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homeassistant/node_modules/eventsource/lib/eventsource.js:159:11)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

@robbiet480 no it just happens randomly, usually after running for 12 hours sometimes longer.

**Comment by robbiet480** [comment] 2016-09-13 21:44
@jsg4 Cool, fix incoming.

**Comment by jsg4** [comment] 2016-09-13 21:44
Screenshot of some of the states

![image](https://cloud.githubusercontent.com/assets/2582639/18492511/aa85db9a-79d9-11e6-833e-b099967a4762.png)

**Comment by robbiet480** [comment] 2016-09-13 21:47
@jsg4 Can you make two really easy edits?

In light.js, line 43, change `if (old_state.state != new_state.state) {` to `if (old_state && old_state.state != new_state.state) {`.

In light.js, line 47, change `if (this.is_supported(this.features.BRIGHTNESS) &&` to `if (this.is_supported(this.features.BRIGHTNESS) && old_state &&`

**Comment by jsg4** [comment] 2016-09-13 23:54
Seeing this error after those edits @robbiet480 

[9/13/2016, 7:53:52 PM] [Living Room Harmony Hub] Found Logitech Harmony remote hub: 192.168.1.32
dgram.js:461
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:461:11)
    at Socket.close (dgram.js:354:8)
    at Ping.stop (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/ping.js:42:14)
    at Explorer.stop (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/explorer.js:82:12)
    at Explorer.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/index.js:88:14)
    at emitOne (events.js:77:13)
    at Explorer.emit (events.js:169:7)
    at Explorer.handleResponse (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/explorer.js:31:8)
    at emitOne (events.js:77:13)
    at ResponseCollector.emit (events.js:169:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/harmonyhubjs-discover/lib/responseCollector.js:31:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
pi@raspberrypi:~ $

**Comment by robbiet480** [comment] 2016-09-13 23:55
@jsg4 That error is unrelated to `homebridge-homeassistant`. May want to file an issue with `homebridge-harmonyhub`.

**Comment by jsg4** [comment] 2016-09-14 00:01
Sorry you're right. Any help with rollershutters and locks not coming through as device types from HomeAssistant?

**Comment by robbiet480** [comment] 2016-09-14 00:03
@jsg4 Just make sure you are on the latest Homebridge and `homebridge-homeassistant` versions and you should be fine. If you're still having trouble please open a new issue.

**Comment by jsg4** [comment] 2016-09-14 00:03
Yeah I am

**Comment by shmuelzon** [comment] 2016-09-14 05:06
@robbiet480 I'm not sure that's the best solution. While it would avoid the exception, it's not the correct behavior. Even if the old_state doesn't exist, we still want to push the new values so HomeKit will be in sync with Home Assistant. I'll create a pull request soon.

@jsg4 HomeAssistant renamed garage doors and rolling shutters to "covers". `homebridge-homeassistant` was not updated to reflect that change so it's not looking for "covers".

**Comment by shmuelzon** [comment] 2016-09-14 05:28
@robbiet480 So, as I was writing the commit message to the pull request, a though occurred: Do we event care about the old_state? Is there any reason to actually compare the two? Worst case scenario we send unneeded events, e.g. send that the light was turned on even if it's already on. Does that warrant the extra conditions?

**Comment by robbiet480** [comment] 2016-09-14 05:29
@shmuelzon I don't think we care, no.

**Closed** 2016-09-14 06:08 UTC
