### ISSUE TITLE
Nest thermostat target temperature not working on homekit

### ISSUE THREAD

**Issue by mceres** [home-assistant/homebridge-homeassistant#243] opened 2017-10-27 03:14 UTC
When trying to change temperature for thermostat in homekit it’s not working. It does work when using homeassistant directly. 

Here is part of the log. It seems that for setting the temperature is trying to use Celsius in homekit. And when I change the target temperature on homeassistant it is using Fahrenheit. 

[2017-10-26 22:04:55] [HomeAssistant] fetching power state for: Living Room
[2017-10-26 22:04:55] [HomeAssistant] fetching Current Heating Cooling state for: Living Room (Living Room)
[2017-10-26 22:04:55] [HomeAssistant] fetching power state for: Living Room DirecTV
[2017-10-26 22:05:20] [HomeAssistant] Received event: ping
[2017-10-26 22:05:30] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.05, "azimuth": 276.99, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:04:30.978588+00:00"}, "new_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.27, "azimuth": 277.13, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:05:30.979266+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:05:30.979315+00:00"}
[2017-10-26 22:05:45] [HomeAssistant] Setting temperature on the 'Living Room (Living Room)' to 22.5
[2017-10-26 22:05:45] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "climate", "service": "set_temperature", "service_data": {"entity_id": "climate.living_room_living_room", "temperature": 22.5}, "service_call_id": "140131611104648-40"}, "origin": "LOCAL", "time_fired": "2017-10-27T03:05:45.246569+00:00"}
[2017-10-26 22:05:55] [HomeAssistant] Successfully set temperature of 'Living Room (Living Room)'
[2017-10-26 22:05:55] [HomeAssistant] Setting temperature on the 'Living Room (Living Room)' to 22
[2017-10-26 22:05:55] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "climate", "service": "set_temperature", "service_data": {"entity_id": "climate.living_room_living_room", "temperature": 22}, "service_call_id": "140131611104648-41"}, "origin": "LOCAL", "time_fired": "2017-10-27T03:05:55.334490+00:00"}
[2017-10-26 22:06:05] [HomeAssistant] Successfully set temperature of 'Living Room (Living Room)'
[2017-10-26 22:06:05] [HomeAssistant] Setting temperature on the 'Living Room (Living Room)' to 21.5
[2017-10-26 22:06:05] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "climate", "service": "set_temperature", "service_data": {"entity_id": "climate.living_room_living_room", "temperature": 21.5}, "service_call_id": "140131611104648-42"}, "origin": "LOCAL", "time_fired": "2017-10-27T03:06:05.385087+00:00"}
[2017-10-26 22:06:15] [HomeAssistant] Successfully set temperature of 'Living Room (Living Room)'
[2017-10-26 22:06:30] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.27, "azimuth": 277.13, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:05:30.979266+00:00"}, "new_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.49, "azimuth": 277.26, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:06:30.979039+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:06:30.979077+00:00"}
[2017-10-26 22:06:58] [HomeAssistant] Received event: {"event_type": "call_service", "data": {"domain": "climate", "service": "set_temperature", "service_data": {"temperature": 74, "entity_id": "climate.living_room_living_room"}, "service_call_id": "140131611104648-43"}, "origin": "LOCAL", "time_fired": "2017-10-27T03:06:58.940779+00:00"}
[2017-10-26 22:07:00] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "climate.living_room_living_room", "old_state": {"entity_id": "climate.living_room_living_room", "state": "cool", "attributes": {"current_temperature": 75, "min_temp": 50, "max_temp": 90, "temperature": 75, "fan_mode": "on", "fan_list": ["on", "auto"], "operation_mode": "cool", "operation_list": ["off", "heat", "cool", "auto", "eco"], "away_mode": "off", "unit_of_measurement": "\u00b0F", "friendly_name": "Living Room (Living Room)"}, "last_changed": "2017-10-27T01:26:56.984206+00:00", "last_updated": "2017-10-27T02:50:04.983503+00:00"}, "new_state": {"entity_id": "climate.living_room_living_room", "state": "cool", "attributes": {"current_temperature": 74, "min_temp": 50, "max_temp": 90, "temperature": 74, "fan_mode": "auto", "fan_list": ["on", "auto"], "operation_mode": "cool", "operation_list": ["off", "heat", "cool", "auto", "eco"], "away_mode": "off", "unit_of_measurement": "\u00b0F", "friendly_name": "Living Room (Living Room)"}, "last_changed": "2017-10-27T01:26:56.984206+00:00", "last_updated": "2017-10-27T03:07:00.340438+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:00.340475+00:00"}
[2017-10-26 22:07:00] [HomeAssistant] Received event: {"event_type": "service_executed", "data": {"service_call_id": "140131611104648-43"}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:00.346712+00:00"}
[2017-10-26 22:07:00] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sensor.living_room_thermostat_living_room_target", "old_state": {"entity_id": "sensor.living_room_thermostat_living_room_target", "state": "75", "attributes": {"unit_of_measurement": "\u00b0F", "friendly_name": "Living Room Thermostat (Living Room) target"}, "last_changed": "2017-10-27T02:03:52.739391+00:00", "last_updated": "2017-10-27T02:03:52.739391+00:00"}, "new_state": {"entity_id": "sensor.living_room_thermostat_living_room_target", "state": "74", "attributes": {"unit_of_measurement": "\u00b0F", "friendly_name": "Living Room Thermostat (Living Room) target"}, "last_changed": "2017-10-27T03:07:00.978092+00:00", "last_updated": "2017-10-27T03:07:00.978092+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:00.978115+00:00"}
[2017-10-26 22:07:00] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sensor.living_room_thermostat_living_room_temperature", "old_state": {"entity_id": "sensor.living_room_thermostat_living_room_temperature", "state": "75", "attributes": {"unit_of_measurement": "\u00b0F", "friendly_name": "Living Room Thermostat (Living Room) temperature"}, "last_changed": "2017-10-27T02:36:11.683369+00:00", "last_updated": "2017-10-27T02:36:11.683369+00:00"}, "new_state": {"entity_id": "sensor.living_room_thermostat_living_room_temperature", "state": "74", "attributes": {"unit_of_measurement": "\u00b0F", "friendly_name": "Living Room Thermostat (Living Room) temperature"}, "last_changed": "2017-10-27T03:07:00.991150+00:00", "last_updated": "2017-10-27T03:07:00.991150+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:00.991179+00:00"}
[2017-10-26 22:07:01] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sensor.living_room_thermostat_living_room_hvac_state", "old_state": {"entity_id": "sensor.living_room_thermostat_living_room_hvac_state", "state": "cooling", "attributes": {"friendly_name": "Living Room Thermostat (Living Room) hvac state"}, "last_changed": "2017-10-27T02:50:02.767933+00:00", "last_updated": "2017-10-27T02:50:02.767933+00:00"}, "new_state": {"entity_id": "sensor.living_room_thermostat_living_room_hvac_state", "state": "off", "attributes": {"friendly_name": "Living Room Thermostat (Living Room) hvac state"}, "last_changed": "2017-10-27T03:07:00.998053+00:00", "last_updated": "2017-10-27T03:07:00.998053+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:00.998173+00:00"}
[2017-10-26 22:07:09] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "binary_sensor.living_room_thermostat_living_room_fan", "old_state": {"entity_id": "binary_sensor.living_room_thermostat_living_room_fan", "state": "on", "attributes": {"friendly_name": "Living Room Thermostat (Living Room) fan"}, "last_changed": "2017-10-27T02:50:12.982207+00:00", "last_updated": "2017-10-27T02:50:12.982207+00:00"}, "new_state": {"entity_id": "binary_sensor.living_room_thermostat_living_room_fan", "state": "off", "attributes": {"friendly_name": "Living Room Thermostat (Living Room) fan"}, "last_changed": "2017-10-27T03:07:09.982470+00:00", "last_updated": "2017-10-27T03:07:09.982470+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:09.982540+00:00"}
[2017-10-26 22:07:30] [HomeAssistant] Received event: {"event_type": "state_changed", "data": {"entity_id": "sun.sun", "old_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.49, "azimuth": 277.26, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:06:30.979039+00:00"}, "new_state": {"entity_id": "sun.sun", "state": "below_horizon", "attributes": {"next_dawn": "2017-10-27T12:15:02+00:00", "next_dusk": "2017-10-28T00:18:32+00:00", "next_midnight": "2017-10-27T06:16:43+00:00", "next_noon": "2017-10-27T18:16:47+00:00", "next_rising": "2017-10-27T12:38:39+00:00", "next_setting": "2017-10-27T23:54:55+00:00", "elevation": -43.72, "azimuth": 277.4, "friendly_name": "Sun"}, "last_changed": "2017-10-26T23:55:44.980304+00:00", "last_updated": "2017-10-27T03:07:30.979138+00:00"}}, "origin": "LOCAL", "time_fired": "2017-10-27T03:07:30.979191+00:00"}

**Comment by schmittx** [comment] 2017-11-07 03:53
Check my comment in #247, I believe the problem is the same...

**Comment by schmittx** [comment] 2018-02-17 23:32
Fixed by #268

**Closed by schmittx** 2018-02-17 23:32 UTC
Labels: bug, climate
